### ISSUE TITLE
A minor bug

### ISSUE THREAD

**Issue by JunMa11** [ihil/PyMIC#1]
Dear @taigw ,

Thanks for sharing the excellent work.

It seems here should be `unet3d` rather than `unet2d5_ag`.

https://github.com/ihil/PyMIC/blob/eaeb496db257b6a58923ecdde25b25be00dd3fe4/pymic/net3d/unet2d5.py#L10

**Comment by taigw** [comment]
Thanks @JunMa11 , the problem has been fixed.
