### ISSUE TITLE
a mirror bug too

### ISSUE THREAD

**Issue by wenwenyu** [ihil/PyMIC#2]
Dear @taigw ，

Thanks for your sharing awesome projects about medical image.

Here seems should be `from pymic.layer` rather than `from pyMIC.layer` in `pymic/net3d/unet3dsep.py` file, line7&8,  as follows
`from pyMIC.layer.activation import get_acti_func`
`from pyMIC.layer.deconvolution import DeconvolutionLayer`

**Comment by taigw** [comment]
@wenwenyu Thanks Wenwen. That file was a temporary file for development and should not be contained in the release. Thanks for pointing this out. I have removed that file.
